version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: npm install
            - run:
                name: Build project 
                command: npm run compile
            - save_cache:
                key: source-v1-{{ .Branch }}-{{ .Revision }}
                paths:
                    - "dist"
                    - "package.json"
                    - "node_modules"
                
                
    deploy:
        machine:
            image: ubuntu-1604:201903-01
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "14:c7:1b:11:67:10:00:7e:bd:9f:52:2f:22:53:07:50"
            - restore_cache:
                keys:
                    - source-v1-{{ .Branch }}-{{ .Revision }}
            # Copy over the projects files to the server
            - run:
                name: Create directory on remote server if it doesn't exist
                command: |
                    ssh focusmf@focusmf.club -t mkdir -p focusmf/backend

            - run:
                name: Copy of Dist and commands to Server
                command: |
                    rsync -va . focusmf@focusmf.club:~/focusmf/backend

            
            - run:
                name: Run TypeORM Migration
                command: |
                    ssh focusmf@focusmf.club -t 'cd ~/focusmf/backend ; npm run typeorm migration:run'

workflows:
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
