swagger: "2.0"

info:
  version: 1.0.0
  title: Focus.MF API
  description: Focus.mf api here is a new description.

schemes:
  - https
host: localhost:3000
basePath: /v1/

tags:
- name: "Utility"
  description: "All service utility functions"
- name: "User"
  description: "All user account functions"

paths:
  /health:
    get:
      tags:
      - "Utility"
      summary: Get service status
      description: Returns the health status of the API service.
      responses:
        200:

  /user:
    get:
      tags:
      - "User"
      summary: Gets some persons
      description: Returns a list containing all persons.
      responses:
        200:
          description: A list of Person
          schema:
            type: array
            items:
              required:
                - username
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                username:
                  type: string