openapi: "3.0.2"

info:
  version: 1.0.0
  title: Focus.MF API
  description: Focus.mf API supports the API commands for the focus.mf service.
  # contact:
  #   name: Focus.MF API
  #   url: "https://focus.mf/api"
  #   email: "focus@focus.mf"

servers:
- url: http://localhost:3000/
  description: Local development

tags:
- name: "Utility"
  description: "All service utility endpoints"
- name: "User"
  description: "All user account endpoints"

paths:
  /health:
    get:
      tags:
      - "Utility"
      summary: Get service status
      description: Returns the health status of the API service.
      responses:
        200:
          description: Backend service health status
          content:
            application/json:
              schema:
                title: Sample
                type: object
                properties:
                  status:
                    type: string
                    description: Returns 'UP' if the server is currently up and running.

  /user:
    get:
      tags:
      - "User"
      summary: Gets some persons
      description: Returns a list containing all persons.
      responses:
        200:
          description: A list of Person
          schema:
            type: array
            items:
              required:
                - username
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                username:
                  type: string